language: node_js
node_js:
  - '7.9'
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
branches:
  only:
    - master
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - npm run build
after_success:
  - scp -r ./dist/* root@cerebroapp.com:/var/www/cerebroapp